### ISSUE TITLE
Not Able To find The CinnamonRoleServiceProvider class

### ISSUE THREAD

**Issue by phppirate** [Mission-4/cinnamon-role#2]

**Comment by willmkt** [comment]
Hi, i´m getting this error with laravel 5.4

**Comment by phppirate** [comment]
What version of the package are you trying to install. It should not happen with the latest version.

**Comment by willmkt** [comment]
I´m using the latest version with laravel 5.4

I just did a fresh install and got the same error.

  [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'App\Providers\CinnamonRole' not found

**Comment by phppirate** [comment]
Can you run `composer info | grep cinnamon` and confirm you see:
```
mission4/cinnamon-role                1.0.5   Laravel Role Package
```

**Comment by willmkt** [comment]
I just did a composer update and got the latest version, but still getting same error.
 
after i ran composer info | grep cinnamon

mission4/cinnamon-role                1.0.5   Laravel Role Package

**Comment by phppirate** [comment]
Can you send me the whole error.

**Comment by boyamahero** [comment]
@willmkt Can you add below  in AuthServiceProvider
`use \Mission4\CinnamonRole\CinnamonRole;`

**Comment by willmkt** [comment]
It worked....
Tahnks @boyamahero
